#!/usr/bin/env php
<?php
if (!defined('PHP_VERSION_ID') || PHP_VERSION_ID < 70000 || PHP_VERSION_ID >= 70300) {
    fwrite(STDERR, "PHP needs to be a minimum version of PHP 7.0.0 and maximum version of PHP 7.2.*.\n");
    exit(1);
}
require_once __DIR__.'/vendor/autoload.php';
use LicenseAdvisor\Application;

(new Application())->run();
